
export const ADD_UNIVERSITY = "UNIVERSITY_ADD";
/*export const DELETE_UNIVERSITY = "UNIVERSITY_DELETE";
export const EDIT_UNIVERSITY = "UNIVERSITY_EDIT";*/
export const COMMENTADD_UNIVERSITY = "UNIVERSITY_COMMENTADD";
export const ADD_APPLICATION = "APPLICATION_ADD";
export const SIGNUP = "SIGNUP";
export const SIGNIN = "SIGNIN";
